<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="urn:country" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:country">
<types>
<xsd:schema targetNamespace="urn:country"
>
 <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
 <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/" />
</xsd:schema>
</types>
<message name="get_infoRequest">
  <part name="country_iso" type="xsd:string" />
  <part name="operation" type="xsd:string" /></message>
<message name="get_infoResponse">
  <part name="response" type="xsd:string" /></message>
<portType name="country info servicePortType">
  <operation name="get_info">
    <input message="tns:get_infoRequest"/>
    <output message="tns:get_infoResponse"/>
  </operation>
</portType>
<binding name="country info serviceBinding" type="tns:country info servicePortType">
  <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="get_info">
    <soap:operation soapAction="http://localhost/to_code3_2/WS1/country_info_service.php/get_info" style="rpc"/>
    <input><soap:body use="encoded" namespace="" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></input>
    <output><soap:body use="encoded" namespace="" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></output>
  </operation>
</binding>
<service name="country info service">
  <port name="country info servicePort" binding="tns:country info serviceBinding">
    <soap:address location="http://localhost/to_code3_2/WS1/country_info_service.php"/>
  </port>
</service>
</definitions>